### ISSUE TITLE
Popups not consistently poppin' up

### ISSUE THREAD

**Issue by alukach** [cugos/dropchop#152] opened 2015-06-20 01:16 UTC
I find that popups work for some datasets and not for others.

**Working:**

http://dropchop.io/?url=http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_day.geojson

Looking at a point from this given dataset, it appears that the `properties.title` field is being rendered as the popup:

```geojson
{
  "type":"Feature",
  "properties":{
    "mag":4.7,
    "place":"135km NE of Naze, Japan",
    "time":1434717017130,
    "updated":1434745972799,
    "tz":540,
    "url":"http://earthquake.usgs.gov/earthquakes/eventpage/us10002k7n",
    "detail":"http://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us10002k7n.geojson",
    "felt":null,
    "cdi":null,
    "mmi":null,
    "alert":null,
    "status":"reviewed",
    "tsunami":0,
    "sig":340,
    "net":"us",
    "code":"10002k7n",
    "ids":",us10002k7n,",
    "sources":",us,",
    "types":",cap,geoserve,nearby-cities,origin,phase-data,tectonic-summary,",
    "nst":null,
    "dmin":2.238,
    "rms":0.63,
    "gap":128,
    "magType":"mb",
    "type":"earthquake",
    "title":"M 4.7 - 135km NE of Naze, Japan"
  },
  "geometry":{
    "type":"Point",
    "coordinates":[
      130.4331,
      29.2639,
      31.43
    ]
  },
  "id":"us10002k7n"
},
```
**Not Working:**

http://dropchop.io/?gist=8385178

Note that, in the not-working example, popups do in fact function on the Github Gist page: https://gist.github.com/tts/8385178

Looking at the code, it appears that the `properties.popupContent` field is being rendered as a key-value table as the popup on Github.

![screen shot 2015-06-19 at 7 22 50 pm](https://cloud.githubusercontent.com/assets/897290/8265510/5c3209a2-16b9-11e5-8971-7925fc972fc9.png)

```geojson
{
  "type":"Feature",
  "geometry":{
    "type":"Point",
    "coordinates":[
      -78.67,
      -1.65
    ]
  },
  "properties":{
    "marker-symbol":"park2",
    "marker-color":"#ff4444",
    "popupContent":"Araucaria angustifolia (Bertol.) Kuntze"
  }
}
```

Perhaps Github opts to render any non-standard entry in `properties` as a row in the table.  Either way, we should do our best to support as much data in the popup as possible...  Maybe put anything in `properties` in the popup?

**Comment by mapsam** [comment] 2015-06-21 17:38
I think this is related to mapbox.js - since they look for some property names, such as `title` and will render a popup if it exists. I would opt to doing what geojson.io and github do and show all property names and values.

**Comment by mapsam** [comment] 2015-09-13 16:57
@alukach going to close this since it's related to the mapbox.js defaults and not a bug on our part. Popups haven't been styled or added yet!

**Closed by mapsam** 2015-09-13 16:57 UTC
Labels: bug, wontfix
